"""PDF rendering for the compliance report.

Internal module: `_ReportPDF` is an fpdf2 subclass carrying the report's
styling helpers, and the row builders translate bundle/record dicts into
the table rows it draws. Not part of the package's public API.
"""

from __future__ import annotations

from typing import Any

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from reporting.obligations import CLAUSE_DESCRIPTION, OBLIGATION_MAP, _field_present


def _format_value(value: Any) -> str:
    if value is None:
        return "-"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, list):
        return ", ".join(str(v) for v in value) if value else "-"
    return str(value)


def _bundle_metadata_rows(bundle: dict[str, Any]) -> list[tuple[str, str]]:
    return [
        ("bundle_id", bundle["bundle_id"]),
        ("pipeline_id", bundle["pipeline_id"]),
        ("session_id", bundle["session_id"]),
        ("protocol_version", bundle.get("protocol_version", "-")),
        ("created_at", bundle.get("created_at", "-")),
        ("disclosure_presented", _format_value(bundle.get("disclosure_presented"))),
        ("bundle_hash", bundle.get("bundle_hash", "-")),
    ]


def _record_summary_rows(bundle: dict[str, Any]) -> list[tuple[str, str]]:
    counts: dict[str, int] = {}
    for record in bundle["records"]:
        rt = record.get("record_type", "unknown")
        counts[rt] = counts.get(rt, 0) + 1
    rows = [("total records", str(len(bundle["records"])))]
    for rt in sorted(counts):
        rows.append((rt, str(counts[rt])))
    return rows


def _record_field_rows(record: dict[str, Any]) -> list[tuple[str, str]]:
    skip = {"record_type", "protocol_version"}
    return [
        (key, _format_value(record[key]))
        for key in record
        if key not in skip
    ]


def _record_clause_rows(record: dict[str, Any]) -> list[tuple[str, str]]:
    mapping = OBLIGATION_MAP.get(record.get("record_type"), {})
    seen: dict[str, None] = {}
    for field, clauses in mapping.items():
        if _field_present(record, field):
            for clause in clauses:
                seen.setdefault(clause, None)
    return [(clause, CLAUSE_DESCRIPTION.get(clause, "")) for clause in seen]


def _coverage_rows(
    coverage: dict[str, list[str]],
) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for clause, ids in coverage.items():
        satisfied = f"{len(ids)} record(s)" if ids else "- not satisfied -"
        rows.append((clause, CLAUSE_DESCRIPTION[clause], satisfied))
    return rows


class _ReportPDF(FPDF):
    """fpdf2 subclass with the styling helpers used by ComplianceReport."""

    BODY_FONT = "Helvetica"
    MONO_FONT = "Courier"

    def __init__(self, bundle_id: str) -> None:
        super().__init__(unit="mm", format="A4")
        self._bundle_id_short = bundle_id[:8]
        self.set_margins(left=18, top=18, right=18)

    def header(self) -> None:
        if self.page_no() == 1:
            return
        self.set_font(self.BODY_FONT, "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, f"Compliance report | bundle {self._bundle_id_short}...")
        self.set_x(-30)
        self.cell(
            0, 6, f"Page {self.page_no()}", align="R",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def footer(self) -> None:
        self.set_y(-14)
        self.set_font(self.BODY_FONT, "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Generated by reporting.compliance_report", align="C")
        self.set_text_color(0, 0, 0)

    def render_title(self, text: str) -> None:
        self.set_font(self.BODY_FONT, "B", 18)
        self.cell(0, 10, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def render_subtitle(self, text: str) -> None:
        self.set_font(self.BODY_FONT, "", 10)
        self.set_text_color(90, 90, 90)
        self.cell(0, 6, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)
        self.ln(2)

    def section_heading(self, text: str) -> None:
        if self.get_y() > 30:
            self.ln(4)
        self.set_font(self.BODY_FONT, "B", 12)
        self.set_fill_color(230, 230, 235)
        self.cell(0, 7, f" {text}", fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(1)

    def subsection(self, text: str) -> None:
        self.ln(1)
        self.set_font(self.BODY_FONT, "B", 10)
        self.cell(0, 5, text, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def kv_table(self, rows: list[tuple[str, str]]) -> None:
        with self.table(
            col_widths=(38, 62),
            text_align=("LEFT", "LEFT"),
            line_height=5,
            borders_layout="MINIMAL",
        ) as table:
            for key, value in rows:
                row = table.row()
                self.set_font(self.BODY_FONT, "B", 9)
                row.cell(key)
                self.set_font(self._value_font(value), "", 9)
                row.cell(value)
        self.ln(1)

    def two_col_table(
        self,
        headers: tuple[str, str],
        rows: list[tuple[str, str]],
    ) -> None:
        with self.table(
            col_widths=(25, 75),
            text_align=("LEFT", "LEFT"),
            line_height=5,
            borders_layout="MINIMAL",
        ) as table:
            header = table.row()
            self.set_font(self.BODY_FONT, "B", 9)
            for h in headers:
                header.cell(h)
            self.set_font(self.BODY_FONT, "", 9)
            for left, right in rows:
                row = table.row()
                row.cell(left)
                row.cell(right)
        self.ln(1)

    def three_col_table(
        self,
        headers: tuple[str, str, str],
        rows: list[tuple[str, str, str]],
    ) -> None:
        with self.table(
            col_widths=(22, 55, 23),
            text_align=("LEFT", "LEFT", "LEFT"),
            line_height=5,
            borders_layout="MINIMAL",
        ) as table:
            header = table.row()
            self.set_font(self.BODY_FONT, "B", 9)
            for h in headers:
                header.cell(h)
            self.set_font(self.BODY_FONT, "", 9)
            for a, b, c in rows:
                row = table.row()
                row.cell(a)
                row.cell(b)
                row.cell(c)
        self.ln(1)

    def _value_font(self, value: str) -> str:
        return self.MONO_FONT if _looks_like_token(value) else self.BODY_FONT


def _looks_like_token(value: str) -> bool:
    if not isinstance(value, str):
        return False
    if len(value) < 16:
        return False
    return all(ch in "0123456789abcdef-:T.Z" for ch in value)
